### ISSUE TITLE
[Enhancement] ParchmentMc Mappings

### ISSUE THREAD

**Issue by MrNavaStar** [MaxPixelStudios/MinecraftDecompiler#123]
**Is your enhancement related to a problem? Please describe.**
More mappings options

**Describe the solution you'd like**
Support for a new mapping

**Additional context**
https://parchmentmc.org/

**Comment by XiaoPangxie732** [comment]
Parchmen support has been added. However, you have to manually specify the mapping format using `-M parchment`. Also, since chaining mappings is not supported, you have to do 2 executions(obf -> official -> parchment) for now
