### ISSUE TITLE
[Enhancement] Add a cli option to output the java source files insted of a jar file

### ISSUE THREAD

**Issue by Coolchickenguy** [MaxPixelStudios/MinecraftDecompiler#165]
**Is your enhancement related to a problem? Please describe.**
I am working on a minecraft server, and I need to decompile mojang's server to see how world generation works. This repo has been very useful, but I would like to not have to decompile the result.

**Describe the solution you'd like**
Adding a cli option to output the java source files of the minecraft jar to a folder

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by XiaoPangxie732** [comment]
`-d` may be the thing you want

**Comment by Coolchickenguy** [comment]
That works! Thank!

**Comment by Coolchickenguy** [comment]
Just asking, what is the best option for -d? I used fernflower, but it spammed the terminal with error messages.

**Comment by XiaoPangxie732** [comment]
the default is the best option
also, you can use the snapshot version([download here](https://github.com/MaxPixelStudios/MinecraftDecompiler/actions/runs/10646266312/artifacts/1877932899)), it contains a newer version of the decompiler

**Comment by Coolchickenguy** [comment]
Vineflower crashed halfway when I used it. ( I have 3 gigs of ram )

**Comment by XiaoPangxie732** [comment]
you can try the snapshot version above, it contains a newer version of vineflower which has an optimized memory usage
but I don't know whether 3 GB RAM is enough

**Comment by Coolchickenguy** [comment]
Ok I will use my computer with 16 gigs
