### ISSUE TITLE
[BUG] [2.4-RELEASE] There is a lot of garbled code in the decompiled code

### ISSUE THREAD

**Issue by SNWCreations** [MaxPixelStudios/MinecraftDecompiler#22]
**Describe the bug**
There is a lot of garbled code in the decompiled code.
I don't think this may be a problem with this program, but I want help.

**To Reproduce**
1. Decompile Minecraft 1.16.5 with Official mapping.
2. Open source codes with IntelliJ IDEA.
3. Too many grabled codes here!!!

**Expected behavior**
A clear and concise description of what you expected to happen. Delete this section if the expected behavior is obvious

**Screenshots**
![QQ截图20210822195932](https://user-images.githubusercontent.com/59989459/130354335-632bc08e-53c1-4cbf-8d4b-87ab71123973.png)

**Logs**
No log, thanks.

**System Info:**
 - OS: Windows 7
 - Arch:: x64
 - Java: AdoptOpenJDK HotSpot 16
 - MinecraftDecompiler Version 2.4-Release

**Comment by XiaoPangxie732** [comment]
This is a ForgeFlower bug. You could try again with `-r` option.
And I found a bug and fixed it just now. So you need to [use the latest build artifact](https://github.com/MaxPixelStudios/MinecraftDecompiler/suites/3562921648/artifacts/85509537) to make sure `-r` option works properly.

**Comment by XiaoPangxie732** [comment]
Hmm... another bug has been found and fixed. Use [this artifact](https://github.com/MaxPixelStudios/MinecraftDecompiler/suites/3562958325/artifacts/85510725) instead.

**Comment by SNWCreations** [comment]
Thank you
This problem is solved. But the readability of the decompiled code is poor.

Anyway, thank you. The problem has been solved.

**Comment by XiaoPangxie732** [comment]
This software only deobfuscates Minecraft and invokes third-party decompilers when decompiling. So I don't have any methods to improve the readability of the decompiled code. If you are confusing with variable names, [ParchmentMC](https://github.com/ParchmentMC) is working on it currently.

**Comment by SNWCreations** [comment]
> This software only deobfuscates Minecraft and invokes third-party decompilers when decompiling. So I don't have any methods to improve the readability of the decompiled code. If you are confusing with variable names, [ParchmentMC](https://github.com/ParchmentMC) is working on it currently.

Thanks! I am not have any questions now.
