### ISSUE TITLE
[BUG] [3.2] Not working (idk english well, sorry)

### ISSUE THREAD

**Issue by kenuna** [MaxPixelStudios/MinecraftDecompiler#96]
**Describe the bug**
not working

**To Reproduce**
1. Pass args '...'
2. See error

Args:
java -jar MinecraftDecompiler.jar "-d USER_DEFINED" arg
pause
(arg = -log=TRACE -dgs=1 -asc=1 -udv=0 -ump=0 -rsy=1 -aoa=1 -e=%lib_repeat% %source% %target%)
**Expected behavior**

**Screenshots**

**Logs**
C:\Users\OS\Desktop\1>java -jar MinecraftDecompiler.jar "-d USER_DEFINED" arg
Exception in thread "main" joptsimple.MissingRequiredOptionsException: Missing required option(s) [m/map/mapping-path, i/input]
        at joptsimple.OptionParser.ensureRequiredOptions(OptionParser.java:435)
        at joptsimple.OptionParser.parse(OptionParser.java:409)
        at cn.maxpixel.mcdecompiler.MinecraftDecompilerCommandLine.main(MinecraftDecompilerCommandLine.java:89)
C:\Users\OS\Desktop\1>pause

**System Info:**
 - OS: [e.g. Windows 10]
 - Arch: [e.g. x64]
 - Java: [JDK 17]
 - MinecraftDecompiler Version [3.2]

**Additional context**
.

**Comment by XiaoPangxie732** [comment]
you passed the wrong args

**Comment by XiaoPangxie732** [comment]
Tell me what you want to do

**Comment by kenuna** [comment]
deobfuscate the plug-in

**Comment by XiaoPangxie732** [comment]
which plugin

**Comment by kenuna** [comment]
buyed plugin, name universal_protect.jar

**Comment by kenuna** [comment]
[protect.zip](https://github.com/MaxPixelStudios/MinecraftDecompiler/files/10483193/protect.zip)

**Comment by XiaoPangxie732** [comment]
oh i forgot, plugins don't need to deobfuscate

**Comment by XiaoPangxie732** [comment]
you can use jd-gui, luyten, recaf, etc.
there are lots of decompilers with gui

**Comment by kenuna** [comment]
![image](https://user-images.githubusercontent.com/107900633/214140655-3c1e656d-082b-412b-986f-51528565e6a7.png)
this plugin obfuscated?

**Comment by XiaoPangxie732** [comment]
yes

**Comment by XiaoPangxie732** [comment]
but MinecraftDecompiler cannot help you
accurately speaking, MinecraftDecompiler is a remapper instead of a deobfuscator/decompiler
